<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBUtil;

/**
 * A selector for an entity in a GTFS feed.
 *
 * Generated from protobuf message <code>transit_realtime.EntitySelector</code>
 */
class EntitySelector extends \Google\Protobuf\Internal\Message
{
    /**
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     *
     * Generated from protobuf field <code>optional string agency_id = 1;</code>
     */
    protected $agency_id = null;
    /**
     * Generated from protobuf field <code>optional string route_id = 2;</code>
     */
    protected $route_id = null;
    /**
     * corresponds to route_type in GTFS.
     *
     * Generated from protobuf field <code>optional int32 route_type = 3;</code>
     */
    protected $route_type = null;
    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
     */
    protected $trip = null;
    /**
     * Generated from protobuf field <code>optional string stop_id = 5;</code>
     */
    protected $stop_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $agency_id
     *           The values of the fields should correspond to the appropriate fields in the
     *           GTFS feed.
     *           At least one specifier must be given. If several are given, then the
     *           matching has to apply to all the given specifiers.
     *     @type string $route_id
     *     @type int $route_type
     *           corresponds to route_type in GTFS.
     *     @type \Transit_realtime\TripDescriptor $trip
     *     @type string $stop_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     *
     * Generated from protobuf field <code>optional string agency_id = 1;</code>
     * @return string
     */
    public function getAgencyId()
    {
        return isset($this->agency_id) ? $this->agency_id : '';
    }

    public function hasAgencyId()
    {
        return isset($this->agency_id);
    }

    public function clearAgencyId()
    {
        unset($this->agency_id);
    }

    /**
     * The values of the fields should correspond to the appropriate fields in the
     * GTFS feed.
     * At least one specifier must be given. If several are given, then the
     * matching has to apply to all the given specifiers.
     *
     * Generated from protobuf field <code>optional string agency_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAgencyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->agency_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string route_id = 2;</code>
     * @return string
     */
    public function getRouteId()
    {
        return isset($this->route_id) ? $this->route_id : '';
    }

    public function hasRouteId()
    {
        return isset($this->route_id);
    }

    public function clearRouteId()
    {
        unset($this->route_id);
    }

    /**
     * Generated from protobuf field <code>optional string route_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteId($var)
    {
        GPBUtil::checkString($var, True);
        $this->route_id = $var;

        return $this;
    }

    /**
     * corresponds to route_type in GTFS.
     *
     * Generated from protobuf field <code>optional int32 route_type = 3;</code>
     * @return int
     */
    public function getRouteType()
    {
        return isset($this->route_type) ? $this->route_type : 0;
    }

    public function hasRouteType()
    {
        return isset($this->route_type);
    }

    public function clearRouteType()
    {
        unset($this->route_type);
    }

    /**
     * corresponds to route_type in GTFS.
     *
     * Generated from protobuf field <code>optional int32 route_type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRouteType($var)
    {
        GPBUtil::checkInt32($var);
        $this->route_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
     * @return \Transit_realtime\TripDescriptor|null
     */
    public function getTrip()
    {
        return $this->trip;
    }

    public function hasTrip()
    {
        return isset($this->trip);
    }

    public function clearTrip()
    {
        unset($this->trip);
    }

    /**
     * Generated from protobuf field <code>optional .transit_realtime.TripDescriptor trip = 4;</code>
     * @param \Transit_realtime\TripDescriptor $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TripDescriptor::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string stop_id = 5;</code>
     * @return string
     */
    public function getStopId()
    {
        return isset($this->stop_id) ? $this->stop_id : '';
    }

    public function hasStopId()
    {
        return isset($this->stop_id);
    }

    public function clearStopId()
    {
        unset($this->stop_id);
    }

    /**
     * Generated from protobuf field <code>optional string stop_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

}

