<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime\Alert;

use UnexpectedValueException;

/**
 * Cause of this alert.
 *
 * Protobuf type <code>transit_realtime.Alert.Cause</code>
 */
class Cause
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_CAUSE = 0;</code>
     */
    const UNKNOWN_CAUSE = 0;
    /**
     * Not machine-representable.
     *
     * Generated from protobuf enum <code>OTHER_CAUSE = 1;</code>
     */
    const OTHER_CAUSE = 1;
    /**
     * Generated from protobuf enum <code>TECHNICAL_PROBLEM = 2;</code>
     */
    const TECHNICAL_PROBLEM = 2;
    /**
     * Public transit agency employees stopped working.
     *
     * Generated from protobuf enum <code>STRIKE = 3;</code>
     */
    const STRIKE = 3;
    /**
     * People are blocking the streets.
     *
     * Generated from protobuf enum <code>DEMONSTRATION = 4;</code>
     */
    const DEMONSTRATION = 4;
    /**
     * Generated from protobuf enum <code>ACCIDENT = 5;</code>
     */
    const ACCIDENT = 5;
    /**
     * Generated from protobuf enum <code>HOLIDAY = 6;</code>
     */
    const HOLIDAY = 6;
    /**
     * Generated from protobuf enum <code>WEATHER = 7;</code>
     */
    const WEATHER = 7;
    /**
     * Generated from protobuf enum <code>MAINTENANCE = 8;</code>
     */
    const MAINTENANCE = 8;
    /**
     * Generated from protobuf enum <code>CONSTRUCTION = 9;</code>
     */
    const CONSTRUCTION = 9;
    /**
     * Generated from protobuf enum <code>POLICE_ACTIVITY = 10;</code>
     */
    const POLICE_ACTIVITY = 10;
    /**
     * Generated from protobuf enum <code>MEDICAL_EMERGENCY = 11;</code>
     */
    const MEDICAL_EMERGENCY = 11;

    private static $valueToName = [
        self::UNKNOWN_CAUSE => 'UNKNOWN_CAUSE',
        self::OTHER_CAUSE => 'OTHER_CAUSE',
        self::TECHNICAL_PROBLEM => 'TECHNICAL_PROBLEM',
        self::STRIKE => 'STRIKE',
        self::DEMONSTRATION => 'DEMONSTRATION',
        self::ACCIDENT => 'ACCIDENT',
        self::HOLIDAY => 'HOLIDAY',
        self::WEATHER => 'WEATHER',
        self::MAINTENANCE => 'MAINTENANCE',
        self::CONSTRUCTION => 'CONSTRUCTION',
        self::POLICE_ACTIVITY => 'POLICE_ACTIVITY',
        self::MEDICAL_EMERGENCY => 'MEDICAL_EMERGENCY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Cause::class, \Transit_realtime\Alert_Cause::class);

